
POST http://rust:8080/embeddings HTTP/1.1
content-type: application/json

{
    "input": ["What is rust"]
}

###

GET http://rust:8080/health HTTP/1.1
content-type: application/json

###

GET http://rust:8080/actors HTTP/1.1
content-type: application/json

###

GET http://rust:8080/invoke/e5 HTTP/1.1
content-type: application/json

{
    "input": ["What is rust"]
}
